# POST http://localhost:3001/api/persons HTTP/1.1
POST https://phonebook-backend-adastros.fly.dev/api/persons HTTP/1.1
content-type: application/json

{
    "name": "popperrrrr",
    "number": 43567
}